version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
